module Structure.Token(Token(..)) where

-- | Intermediate represenation of input. 
-- | Generated by Lexer, processed into Terms by Parser.
data Token =
    V Char        |
    Lambda [Char] |
    LB            |
    RB

-- | Application is left associative.
-- | Abstraction is right associative.